
version: "1.0"
checks:
  root-check:
    type: command
    exec: echo '[{"id":1,"type":"typeA"},{"id":2,"type":"typeB"},{"id":3,"type":"typeA"}]'
    output_format: json
    forEach: true

  check-a:
    type: command
    depends_on: [root-check]
    if: 'outputs["root-check"].type === "typeA"'
    exec: >
      echo '{"processed_id": {{ outputs["root-check"].id }}, "processor": "A"}'
    output_format: json

  check-b:
    type: command
    depends_on: [root-check]
    if: 'outputs["root-check"].type === "typeB"'
    exec: >
      echo '{"processed_id": {{ outputs["root-check"].id }}, "processor": "B"}'
    output_format: json

  final-check:
    type: log
    depends_on: [check-a, check-b]
    message: |
      === Final Check Outputs ===
      All outputs keys: {{ outputs | keys | join: ", " }}
      check-a: {{ outputs["check-a"] | json }}
      check-b: {{ outputs["check-b"] | json }}
      root-check: {{ outputs["root-check"] | json }}
