name = "visor-router"
main = "worker.js"
compatibility_date = "2025-01-14"

# Routes configuration for probelabs.com subdirectory
[[routes]]
pattern = "probelabs.com/visor"
zone_name = "probelabs.com"

[[routes]]
pattern = "probelabs.com/visor/*"
zone_name = "probelabs.com"