version: "1.0"

# Default Visor configuration - provides comprehensive code analysis out-of-the-box
# Uses mock provider for CI compatibility when no AI API keys are configured
# Users can override this by creating their own .visor.yaml in their project root

# Global AI provider settings - users should configure their preferred provider
# For CI testing, use --provider mock CLI flag instead

# Run checks sequentially to ensure session reuse works correctly
max_parallelism: 1

# ðŸ”„ AI Session Reuse Feature:
# This configuration demonstrates the new 'reuse_ai_session' feature that allows
# dependent checks to continue conversations with the same AI session, providing
# context continuity and more intelligent follow-up analysis.
#
# Example: security-remediation reuses the session from the security check,
# allowing the AI to reference the previous security analysis discussion.

# Global fail condition - fail if critical issues are found
fail_if: "output.issues && output.issues.some(i => i.severity === 'critical')"

checks:
  # AI-powered release notes generation - manual execution only for release workflows
  release-notes:
    type: ai
    group: release
    schema: plain
    prompt: |
      Generate professional release notes for version {{ env.TAG_NAME }} of this project.

      Analyze the git commits since the last release:
      ```
      {{ env.GIT_LOG }}
      ```

      And the file changes summary:
      ```
      {{ env.GIT_DIFF_STAT }}
      ```

      Create release notes with these sections:

      ## ðŸš€ What's New in {{ env.TAG_NAME }}

      ### âœ¨ New Features
      List any new features added (look for feat: commits)

      ### ðŸ› Bug Fixes
      List any bugs fixed (look for fix: commits)

      ### ðŸ“ˆ Improvements
      List any improvements or refactoring (look for refactor:, perf:, chore:, build: commits)

      ### ðŸ”¥ Breaking Changes
      List any breaking changes if present (look for BREAKING CHANGE or ! in commits)

      ### ðŸ“Š Statistics
      - Number of commits since last release
      - Number of contributors involved
      - Number of files changed

      Keep descriptions concise and user-friendly. Focus on what changed from a user perspective, not implementation details.
      Use present tense and action-oriented language. Group similar changes together.
    on: [manual]

  # PR overview with intelligent analysis - runs first to establish context
  overview:
    type: ai
    group: overview
    prompt: |
        # ðŸ“‹ Pull Request Overview: {{ pr.title }}

        {% if pr.body %}
        ## Description
        {{ pr.body }}
        {% endif %}

        ## Files Changed Analysis

        | File | Type | Status | Changes | Impact |
        |------|------|--------|---------|--------|
        {% for file in files %}
        | `{{ file.filename }}` | {{ file.filename | split: "." | last | upcase }} | {{ file.status | capitalize }} | +{{ file.additions }}/-{{ file.deletions }} | {% if file.changes > 50 %}High{% elsif file.changes > 20 %}Medium{% else %}Low{% endif %} |
        {% endfor %}

        ## Architecture & Impact Assessment

        Please generate a comprehensive overview and analysis of this pull request.

        Follow these instructions to create a thorough assessment:

        1. **Change Impact Analysis**
           - What this PR accomplishes
           - Key technical changes introduced
           - Affected system components

        2. **Architecture Visualization**
           - Create appropriate mermaid diagram(s) showing:
             - Component relationships (use `graph TD/LR`)
             - Process flows (use `flowchart` or `sequenceDiagram`)
             - Data flow between modified components

        **Guidelines for diagrams:**
        - Use multiple diagrams if there are distinct architectural aspects
        - Choose the most appropriate diagram type for each concept
        - Focus on modified components and their relationships
        - Keep diagrams clean and informative

        Provide a balanced technical assessment suitable for both developers and stakeholders.
    on: [pr_opened, pr_updated]

  # Security analysis - Critical for all projects
  security:
    type: ai
    group: review
    schema: code-review
    prompt: |
        Based on our overview discussion, please perform a comprehensive security analysis of the code changes in this pull request.

        ## Context Available
        You have access to the full PR context in <pull_request> XML tags, including:
        - <metadata> with PR number, title, and change statistics
        - <description> with the PR description
        - <full_diff> containing all code changes
        - <files_summary> listing all modified files with their change details

        ## Instructions
        Analyze the code in <full_diff> for security vulnerabilities including:

        **Input Validation & Injection:**
        - SQL injection in database queries
        - XSS vulnerabilities in user input handling
        - Command injection in system calls
        - Path traversal in file operations

        **Authentication & Authorization:**
        - Weak authentication mechanisms
        - Session management flaws
        - Access control bypasses
        - Privilege escalation opportunities

        **Data Protection:**
        - Sensitive data exposure in logs/errors
        - Unencrypted data storage
        - API key or credential leaks
        - Privacy regulation compliance

        **Infrastructure Security:**
        - Insecure configurations
        - Missing security headers
        - Vulnerable dependencies
        - Resource exhaustion vulnerabilities

        Provide specific findings with clear explanations and actionable remediation steps.
    depends_on: [overview]
    reuse_ai_session: true  # ðŸ”„ Reuses the overview check's AI session for context continuity
    on: [pr_opened, pr_updated]

  # Performance analysis - Important for all applications
  performance:
    type: ai
    group: review
    schema: code-review
    prompt: |
        Building on our overview and security analysis, now review the code changes for performance issues.

        ## Context Available
        The complete PR context is in <pull_request> XML tags. Focus your analysis on:
        - Code changes in <full_diff> (or <commit_diff> for incremental reviews)
        - File change patterns in <files_summary>
        - Scale of changes from <metadata><total_additions> and <metadata><total_deletions>

        ## Analysis Areas
        **Algorithm & Data Structure Efficiency:**
        - Time complexity analysis (O(n), O(nÂ²), etc.)
        - Space complexity and memory usage
        - Inefficient loops and nested operations
        - Suboptimal data structure choices

        **Database Performance:**
        - N+1 query problems
        - Missing database indexes
        - Inefficient JOIN operations
        - Large result set retrievals

        **Resource Management:**
        - Memory leaks and excessive allocations
        - File handle management
        - Connection pooling issues
        - Resource cleanup patterns

        **Async & Concurrency:**
        - Blocking operations in async contexts
        - Race conditions and deadlocks
        - Inefficient parallel processing

        Building on our overview and security analysis, identify performance issues and provide optimization recommendations that complement our previous findings.
    depends_on: [security]
    reuse_ai_session: true  # ðŸ”„ Reuses the security check's AI session for context continuity
    on: [pr_opened, pr_updated]

  # Code quality and maintainability
  quality:
    type: ai
    group: review
    schema: code-review
    prompt: |
        Building on our overview, security, and performance discussions, evaluate the code quality and maintainability.

        ## Context Available
        Review the code changes in <full_diff> within the <pull_request> XML structure.
        The files being changed are listed in <files_summary>.

        ## Quality Assessment Areas
        **Code Structure & Design:**
        - SOLID principles adherence
        - Design pattern appropriateness
        - Separation of concerns
        - Code organization and clarity

        **Error Handling & Reliability:**
        - Exception handling completeness
        - Error propagation patterns
        - Input validation thoroughness
        - Edge case coverage

        **Testing & Test Coverage:**
        - Missing tests for critical functionality
        - Test coverage gaps
        - Test quality and effectiveness
        - Edge cases and error scenarios coverage

        **Maintainability:**
        - Code testability issues
        - Dependencies and coupling problems
        - Technical debt introduction
        - Code duplication (DRY violations)

        **Language-Specific Best Practices:**
        - Idiomatic code usage
        - Framework/library best practices
        - Type safety (if applicable)

        Focus on actionable improvements that enhance code maintainability while considering the overview, security, and performance findings we've already discussed.
    depends_on: [performance]
    reuse_ai_session: true  # ðŸ”„ Reuses the performance check's AI session for context continuity
    on: [pr_opened, pr_updated]

  # Command orchestrator - demonstrates noop type for triggering multiple checks
  review-all:
    type: noop
    command: '/review'
    depends_on: [overview, security, performance, quality]
    on: [issue_comment]
    if: "event.isPullRequest"  # Only trigger on PR comments, not issues
    group: orchestrator

  # Intelligent Issue Assistant - provides sophisticated issue triage and assistance
  issue-assistant:
    type: ai
    group: issue-support
    command: "ask"
    if: "event.name === 'issues' && event.action === 'opened' || (event.name === 'issue_comment' && event.comment && event.comment.body && event.comment.body.trim().startsWith('/ask'))"
    prompt: |
        You are an intelligent GitHub issue assistant for the {{ event.repository.fullName }} repository. Your role is to provide professional, knowledgeable assistance based on the trigger event.

        ## Event Context
        **Event Type**: {{ event.name }} - {{ event.action }}
        {% if event.issue -%}
        **Issue #{{ event.issue.number }}**: {{ event.issue.title }}
        **Author**: {{ event.issue.author }}
        **State**: {{ event.issue.state }}
        **Created**: {{ event.issue.createdAt }}
        {%- if event.issue.labels.size > 0 %}
        **Labels**: {% for label in event.issue.labels %}{{ label.name }}{% unless forloop.last %}, {% endunless %}{% endfor %}
        {%- endif %}
        {%- if event.issue.assignees.size > 0 %}
        **Assignees**: {% for assignee in event.issue.assignees %}{{ assignee }}{% unless forloop.last %}, {% endunless %}{% endfor %}
        {%- endif %}
        {%- endif %}
        {%- if event.comment %}
        **Comment by**: {{ event.comment.author }}
        {%- endif %}

        ## Repository Analysis Context
        {%- if event.isPullRequest and pr.title %}
        **PR Context**: {{ pr.title }}
        {%- endif %}
        {%- if event.repository %}
        **Repository**: {{ event.repository.fullName }}
        {%- endif %}

        ## Instructions

        {%- if event.name == 'issues' and event.action == 'opened' %}

        **ISSUE TRIAGE MODE**

        Analyze this new issue and provide intelligent triage:

        ### Issue Content
        {{ event.issue.body }}

        ### Analysis Tasks
        1. **Categorize** the issue (bug/feature/documentation/question/enhancement/maintenance)
        2. **Assess priority** (low/medium/high/urgent) based on:
           - Impact on users/system
           - Security implications
           - Blocking nature
           - Community interest
        3. **Estimate complexity** (trivial/simple/moderate/complex)
        4. **Suggest timeline** for resolution
        5. **Recommend labels** that would help with organization
        6. **Identify stakeholders** who should be involved or assignees
        7. **Provide initial response** to the issue author

        ### Response Requirements
        - Be professional and welcoming
        - Show you understand the request
        - Provide clear next steps
        - Ask clarifying questions if needed
        - Include technical insights where appropriate

        {%- elsif event.name == 'issue_comment' %}

        **ASSISTANCE MODE**

        A user has asked a question or provided additional information. Provide helpful technical assistance:

        ### Original Issue
        {%- if event.issue.title %}
        **Title**: {{ event.issue.title }}
        {%- endif %}
        {%- if event.issue.body %}
        **Description**: {{ event.issue.body }}
        {%- endif %}

        ### Latest Comment
        {{ event.comment.body }}

        ### Analysis Tasks
        1. **Understand the context** of their question/comment
        2. **Provide technical guidance** based on project knowledge
        3. **Reference relevant code/files** if applicable
        4. **Suggest implementation approaches** for feature requests
        5. **Provide debugging steps** for bug reports
        6. **Link to documentation** or similar issues if helpful
        7. **Offer code examples** when appropriate

        ### Response Requirements
        - Address their specific question directly
        - Provide actionable guidance
        - Be encouraging and supportive
        - Use technical language appropriate to their level
        - Include code examples where helpful
        - Reference project conventions and patterns

        {%- endif %}

        ### Special Instructions
        - Always be professional, helpful, and encouraging
        - Focus on actionable advice and clear next steps
        - Use markdown formatting for better readability
        - Include relevant code examples when helpful
        - Reference project context and patterns when applicable
        - If dealing with `/visor` commands in comments, acknowledge and provide assistance
        - Maintain consistency with project tone and contributor guidelines

        ### Response Format
        Provide a well-structured markdown response with clear sections and helpful guidance.
    on: [issue_opened, issue_comment]

# Output configuration
output:
  pr_comment:
    format: markdown
    group_by: check
    collapse: true