version: "1.0"

# Base configuration for common checks
checks:
  security:
    type: ai
    prompt: |
      Analyze this code for security vulnerabilities:
      - SQL injection
      - XSS vulnerabilities
      - Authentication issues
      - Authorization flaws
    on: [pr_opened, pr_updated]
    group: security
    schema: code-review
    ai_model: gpt-4

  performance:
    type: ai
    prompt: |
      Check for performance issues:
      - Inefficient algorithms
      - Memory leaks
      - Unnecessary computations
    on: [pr_opened]
    group: performance
    schema: code-review

  style:
    type: command
    exec: npx prettier --check .
    on: [pr_opened, pr_updated]
    group: formatting

output:
  pr_comment:
    format: markdown
    group_by: check
    collapse: true
  github_checks:
    enabled: true
    per_check: true

ai_provider: openai
max_parallelism: 3
fail_fast: false