version: "1.0"

# Team-specific configuration extending from base
extends: ./base-config.yaml

# Override some base settings
ai_provider: anthropic
ai_model: claude-3-opus-20240229

checks:
  # Override security check with more specific prompt
  security:
    type: ai
    prompt: |
      Analyze this TypeScript/React code for security vulnerabilities:
      - React-specific XSS vulnerabilities
      - Unsafe dangerouslySetInnerHTML usage
      - Authentication/authorization in React components
      - API key exposure in frontend code
      - CORS configuration issues
    on: [pr_opened, pr_updated]
    group: security
    schema: code-review
    ai_model: claude-3-opus-20240229

  # Add team-specific check
  typescript:
    type: tool
    exec: npx tsc --noEmit
    on: [pr_opened, pr_updated]
    group: validation

  # Add custom test runner
  tests:
    type: tool
    exec: npm test -- --coverage
    on: [pr_opened]
    group: testing

  # Disable style check from base by setting empty 'on' array
  style:
    type: tool
    exec: npx prettier --check .
    on: []

# Team prefers JSON output
output:
  pr_comment:
    format: json
    group_by: file
    collapse: false