name: Release Visor Docs MCP

on:
  push:
    tags:
      - 'mcp-v*'  # Use mcp-v prefix to distinguish from main releases

jobs:
  release:
    uses: probelabs/docs-mcp/.github/workflows/release-mcp.yml@main
    with:
      package-name: '@probelabs/visor-docs-mcp'
      package-description: 'Visor Documentation MCP Server'
      entry-point: 'src/index.js'
      include-folders: 'src,data,bin,lib,docs'
      include-files: '*.json,*.md,LICENSE,README.md'
      build-command: 'npm run build'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}